<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-04-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programari', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
=======
# Generated by Django 4.1.7 on 2023-04-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programari', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
>>>>>>> cfb0182bde54c6a59ce9e3db1fb99632a4161897
